# Docker Compose configuration for H2spec compliance testing
# Split into two parts to prevent probe failures from test accumulation

services:
  # H2spec server that will be tested
  h2spec-server:
    build:
      context: .
      dockerfile: Dockerfile.h2spec
    container_name: ht2-h2spec-server
    hostname: h2spec-server
    networks:
      - h2spec-net
    environment:
      - HT2_LOG_LEVEL=INFO
      - LOG_LEVEL=INFO
    command: ./h2spec_server --host 0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-k", "https://localhost:8443/"]
      interval: 1s
      timeout: 5s
      retries: 30
    restart: always  # Restart if the server crashes

  # H2spec Part 1: Generic tests and HTTP/2 sections up to 6.8
  h2spec-part1:
    image: summerwind/h2spec:2.6.0
    depends_on:
      h2spec-server:
        condition: service_healthy
    networks:
      - h2spec-net
    volumes:
      - ./h2spec-results:/results
    entrypoint: |
      sh -c "
        h2spec -h h2spec-server -p 8443 -t -k \
          generic http2/3 http2/4 http2/5 http2/6.1 http2/6.2 http2/6.3 http2/6.4 http2/6.5 http2/6.7 http2/6.8 \
          | tee /results/part1_results.txt
      "

  # H2spec Part 2: HTTP/2 sections 6.9+ and HPACK
  h2spec-part2:
    image: summerwind/h2spec:2.6.0
    depends_on:
      h2spec-server:
        condition: service_healthy
    networks:
      - h2spec-net
    volumes:
      - ./h2spec-results:/results
    entrypoint: |
      sh -c "
        h2spec -h h2spec-server -p 8443 -t -k \
          http2/6.9.1 http2/6.9.2 http2/6.10 http2/7 http2/8 hpack \
          | tee /results/part2_results.txt
      "

networks:
  h2spec-net:
    driver: bridge